name: Update Cron Schedule

on:
  schedule:
    - cron: '0 18 * * *' # Run daily at 6:00 PM Taipei time (UTC+8)
  workflow_dispatch:  # Enable manual trigger

jobs:
  update-cron:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v2

      - name: Update cron schedule
        run: |
          # Generate a random minute (0-59)
          RANDOM_MINUTE=$((RANDOM % 60))

          # Update the cron expression in the E2NovaCheckIn.sgmodule file
          # Replace the existing minute value for the hourly check
          sed -i "s/cronexp=\"[0-9]* \*/cronexp=\"$RANDOM_MINUTE */" E2NovaCheckIn.sgmodule

      - name: Commit and push changes
        run: |
          # Configure Git with GitHub Action bot details
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # Stage the modified E2NovaCheckIn.sgmodule file
          git add E2NovaCheckIn.sgmodule
          
          # Commit the changes, exiting successfully if no changes to commit
          git commit -m "Update cron schedule" || exit 0
          
          # Push the changes to the repository
          git push
