name: Update Cron Schedule

on:
  schedule:
    - cron: '0 0,10 * * *' # Run daily at 12:00 AM UTC (8:00 AM Taipei time, UTC+8) and 10:00 PM UTC (6:00 PM Taipei time, UTC+8)
  workflow_dispatch:  # Enable manual trigger

jobs:
  update-cron:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v2

      - name: Update cron schedule
        run: |
          # Get current UTC hour and convert to Taipei time (UTC+8)
          CURRENT_HOUR_UTC=$(date -u +"%H")
          TAIPEI_HOUR=$(( (CURRENT_HOUR_UTC + 8) % 24 ))
          echo "Current UTC hour: $CURRENT_HOUR_UTC"
          echo "Current Taipei hour: $TAIPEI_HOUR"
          
          # Set random minute based on Taipei time
          if [ "$TAIPEI_HOUR" -ge 8 ] && [ "$TAIPEI_HOUR" -lt 18 ]; then
            # Between 8 AM and 6 PM Taipei time (working hours)
            # Get current minute value from module file
            CURRENT_MINUTE=$(grep -oP 'cronexp="\K[0-9]+' E2NovaCheckIn.sgmodule)
            echo "Current minute in E2NovaCheckIn.sgmodule: $CURRENT_MINUTE"
            
            # Generate a random number between 1-59, but make sure RANDOM_MINUTE - CURRENT_MINUTE < 30
            MAX_ALLOWED=$((CURRENT_MINUTE + 29))
            if [ $MAX_ALLOWED -gt 59 ]; then
              MAX_ALLOWED=59
            fi
            
            RANDOM_MINUTE=$((1 + RANDOM % MAX_ALLOWED))
            echo "Taipei working hours (8AM-6PM): Generated random minute: $RANDOM_MINUTE (range: 1-$MAX_ALLOWED)"
          else
            # Outside working hours (6PM - 8AM Taipei time)
            # Generate any random minute between 1-59
            RANDOM_MINUTE=$((1 + RANDOM % 59))
            echo "Taipei non-working hours: Generated random minute: $RANDOM_MINUTE (range: 1-59)"
          fi

          # Update the cron expression in the E2NovaCheckIn.sgmodule file
          sed -i "s/cronexp=\"[0-9]* \*/cronexp=\"$RANDOM_MINUTE */" E2NovaCheckIn.sgmodule
          echo "Updated cron expression in E2NovaCheckIn.sgmodule"

      - name: Commit and push changes
        run: |
          # Configure Git with GitHub Action bot details
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # Stage, commit and push changes
          git add E2NovaCheckIn.sgmodule
          git commit -m "Update cron schedule" || echo "No changes to commit"
          git push || echo "Failed to push changes"
