name: Update Cron Schedule

on:
  schedule:
    - cron: '0 0,10 * * *' # Run daily at 12:00 AM UTC (8:00 AM Taipei time, UTC+8) and 10:00 PM UTC (6:00 PM Taipei time, UTC+8)
  workflow_dispatch:  # Enable manual trigger

jobs:
  update-cron:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v2

      - name: Update cron schedule
        run: |
          # Get current UTC hour
          CURRENT_HOUR=$(date -u +"%H")
          echo "Current UTC hour: $CURRENT_HOUR"
          
          # Set random minute range based on time
          if [ "$CURRENT_HOUR" = "00" ]; then
            # Morning execution (8:00 AM Taipei time / 00:00 UTC)
            # Generate random minute between 31-59
            RANDOM_MINUTE=$((31 + RANDOM % 29))
            echo "Morning execution: Generated random minute: $RANDOM_MINUTE (range: 31-59)"
          else
            # Evening execution (6:00 PM Taipei time / 10:00 UTC)
            # Generate random minute between 1-30
            RANDOM_MINUTE=$((1 + RANDOM % 29))
            echo "Evening execution: Generated random minute: $RANDOM_MINUTE (range: 1-30)"
          fi

          # Update the cron expression in the E2NovaCheckIn.sgmodule file
          # Replace the existing minute value for the hourly check
          sed -i "s/cronexp=\"[0-9]* \*/cronexp=\"$RANDOM_MINUTE */" E2NovaCheckIn.sgmodule
          echo "Updated cron expression in E2NovaCheckIn.sgmodule"

      - name: Commit and push changes
        run: |
          # Configure Git with GitHub Action bot details
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          echo "Configured Git with GitHub Action bot details"
          
          # Stage the modified E2NovaCheckIn.sgmodule file
          git add E2NovaCheckIn.sgmodule
          echo "Staged E2NovaCheckIn.sgmodule"
          
          # Commit the changes, exiting successfully if no changes to commit
          git commit -m "Update cron schedule" || echo "No changes to commit"
          
          # Push the changes to the repository
          git push && echo "Changes pushed successfully" || echo "Failed to push changes"
